microsoft/Multi-Agent-Custom-Automation-Engine-Solution-Accelerator

- src/frontend/wwwroot/app.css
- src/frontend/wwwroot/assets/Send.svg
- src/frontend/wwwroot/home/home.css
- src/frontend/wwwroot/home/home.js
- src/frontend/wwwroot/task/task.css
- src/frontend/wwwroot/task/task.js
- Fixed text count does not update on auto clear of textbox (this has been handled for the home and task sections)
- Fixed text count does not update when the 'Quick Task' section is selected from the homepage
- Fixed the Clicking Submit with no task text still creates a task
- Fixed the Long delay after SUBMIT a task with no feedback, causes user to click again
- Fixed the Character count is not updated after submitting chat info, shows prior count
- Fixed the User is still shown the active chat box even when no info is needed
- Fixed the ENTER performs a carriage return, should submit the user text
- Fixed the Clicking a quick task adds text into chat box but char counter is not updated
> fix: ui changes hotfix-1

- src/frontend/wwwroot/task/task.js
After Click on Cancel button notification text is updated.
> Cancel notification message updated

- deploy/macae-continer-oc.json
Generated json with updated bicep template.
In previous PR, Bicep updated but not the JSON. so updating in this PR
> Generated json with updated bicep template

- README.md
Updated readme for accelerator name to be consistent across
> Updated readme for accelerator name to be consistent accross

- src/frontend/wwwroot/task/task.js
dialog view not updating and change not taken when new info added
> fix: dialog view not updating and change not taken when new info added

- src/frontend/wwwroot/task/employee.html
- src/frontend/wwwroot/task/task.css
- src/frontend/wwwroot/task/task.js
Now stages content will not overflow the stages container.
> Stages overflow issue fix

- .github/dependabot.yml
- .github/workflows/sync-branches.yml
Purpose
This PR introduces a new configuration for Dependabot and ensures that dependency updates are managed without disrupting the main branch.
Key Changes:
1.Added a dependabot.yml file:
Configured Dependabot to open pull requests targeting the dependabotchanges branch for dependency updates.
This change allows for testing and validation before merging updates into the main branch.
2.Created a GitHub Action:
Ensures that changes in the dependabotchanges branch are kept in sync with the main branch.
This helps maintain consistency between branches and prevents untested changes from breaking deployments.
> chore: Add Dependabot Configuration with Sync to 'dependentbotchanges' Branch

- src/backend/agents/group_chat_manager.py
> Fix: Added space to the agent

- src/frontend/wwwroot/task/task.js
- Approve and reject buttons titles 
- Disabling start/pause buttons if task is completed.
> Approve reject buttons titles disabling buttons and

- .github/workflows/deploy.yml
The purpose is to update the cosmos location in the `deploy.yml` file to `eastus2` to ensure that the deployment is successful.
> chore: Updated cosmos location

- .github/workflows/deploy.yml
The purpose is to schedule the auto bicep deployment
> feat: scheduled the auto deployment

- .github/workflows/codeql.yml
*Enable the CodeQL for in GitHub Pipeline to scan the codebase for potential security vulnerabilities.
```
cd [repo-name]
npm install
```
NA
* NA
> feat: [POC] Integrate CodeQL Code Quality Tool in Multi-Agent-Custom-Automation-Engine-Solution-Accelerator

- .github/workflows/test.yml
Addition of pytest-asyncio installation
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> chore: Updating the test workflow 

- src/frontend/wwwroot/task/task.js
Text Area will be disabled when  human_clarification_request is null
> fix: Changes of disabling text area functionality

- src/frontend/wwwroot/app.html
- src/frontend/wwwroot/home/home.css
- src/frontend/wwwroot/home/home.html
- src/frontend/wwwroot/task/task.css
After changes
**1 Stage view**
**6 Stages view**
> fix: Usability and Alignments changes

- src/frontend/wwwroot/task/task.css
- src/frontend/wwwroot/task/task.js
Text area Input background color will be grayed out when disabled.
> fix: text area background color

- src/frontend/wwwroot/app.css
* This pull request includes a change to the `src/frontend/wwwroot/app.css` file to modify the maximum height of the `.menu-list` class.
Styling adjustment:
* [`src/frontend/wwwroot/app.css`](diffhunk://#diff-ff4d53ae9345a628a61542105398e8d6b30e1ca9ebf086b3dde29ac51dbec561L214-R214): Changed the `max-height` property of the `.menu-list` class from a fixed value of `300px` to a calculated value of `calc(100vh - 450px)`.
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: ui issue where, after creating more than 4 tasks, the 5th task does not appear

- src/backend/Dockerfile
* In backend - docker file I changed the path from "app/backend" to "src/backend" for resolve the container issue when deployment.
> fix: File path changed for backend to resolve container issue

- src/frontend/wwwroot/task/task.js
* Fix bug (14021) to ensure chat is disabled after receiving a human clarification response from the user.
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: Fixed bug to disable chat after receiving human clarification response

- .github/workflows/deploy.yml
- deploy/scripts/checkquota.sh
* ...
This pull request introduces a new quota check mechanism to the deployment pipeline and adjusts the deployment region configuration based on the quota availability. The most important changes include adding a quota check step, sending notifications on quota failure, and updating the deployment region dynamically.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R17-R59): Added a new step to run a quota check script and set a flag if the quota is insufficient.
* [`deploy/scripts/checkquota.sh`](diffhunk://#diff-4770a7ba509aa12018b79c9b3cf5bf22cab945f672e887c72c7a953f8a65874cR1-R97): Introduced a new script to check Azure regions for sufficient quota for specific models and set the deployment region accordingly.
* …
> ci: implement quota check in CI Pipeline to ensure resource availability in supported region

- .github/workflows/deploy.yml
* ...
This pull request includes a change to the deployment workflow configuration in the `.github/workflows/deploy.yml` file. The change reduces the `GPT_MIN_CAPACITY` value to optimize resource usage.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L24-R24): Reduced the `GPT_MIN_CAPACITY` from "130" to "50" to optimize resource usage.
No
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: updated capacity according to bicep configuration

- deploy/macae-continer-oc.json
- deploy/macae-continer.bicep
- deploy/macae-dev.bicep
- deploy/macae-large.bicepparam
- deploy/macae-mini.bicepparam
- deploy/macae.bicep
Deploy Cosmos DB as Serverless Instead of Shared Database Throughput.
```
cd [repo-name]
npm install
```
```
```
* ...
> chore: Deploy Cosmos DB as Serverless Instead of Shared Database Throughput

- src/frontend/wwwroot/task/task.js
* After cancelling the task, user still can provide the input
- [] No
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: After cancelling the task, user still can provide the input

- src/frontend/wwwroot/utils.js
Maximum call stack size exceeded issue 
```
cd [repo-name]
npm install
```
> fix: Maximum call stack size exceeded

- src/backend/app_config.py
- src/backend/kernel_agents/planner_agent.py
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Planner agent updated

- infra/main.bicep
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Gpickett patch 2

- .github/workflows/deploy.yml
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: Consistent Deployment Name updated

- infra/main.bicep
* ...
Change from Premium to Basic SKU for website to avoid resources issues with some subscriptions
```
cd [repo-name]
npm install
```
```
```
* ...
> change p to b sku

- .azdo/pipelines/azure-dev.yml
- .github/workflows/azure-dev.yml
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> validation

- infra/main.bicep
Reverts microsoft/Multi-Agent-Custom-Automation-Engine-Solution-Accelerator#140
> Revert "Update main.bicep"

- infra/main.bicep
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fixing validation pipeline

- README.md
This pull request includes a minor fix to the `README.md` file. The change corrects a typo in the word "authentication" within the `Additional Steps` section.
> docs: There was a typo error in Add an Authentication step. Updated README.md

- src/backend/kernel_agents/agent_base.py
- src/backend/kernel_agents/group_chat_manager.py
- src/backend/kernel_agents/planner_agent.py
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: missing context 

- src/backend/app_kernel.py
- src/backend/event_utils.py
- src/backend/kernel_agents/agent_factory.py
- src/frontend/wwwroot/task/task.js
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: add back telemetry and close project client

- documentation/DeploymentGuide.md
- infra/main.bicep
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> feat: quote

- src/backend/app_kernel.py
* ...Currently local debug fails as configure_azure_monitor required a connection_string for that param
- [x ] No
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: to pass con str instead of key

- azure.yaml
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> add telemetry tag

- src/backend/requirements.txt
Added version in requirement file for these packages
semantic-kernel[azure] 1.28.1
azure-ai-projects 1.0.0b10
azure-ai-inference 1.0.0b9
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> docs: Change Version of packages in requirment.txt

- README.md
* ...
update readme file text 
```
cd [repo-name]
npm install
```
```
```
* ...
> feat: Add calculator template to readme

- infra/main.bicep
- infra/main.json
This pull request introduces several changes to the infrastructure configuration, primarily focusing on improving naming conventions, updating dependencies, and simplifying resource references. The key updates include replacing the `prefix` parameter with a dynamically generated `solutionPrefix`, updating the Bicep version, and refining resource references for better maintainability.
* Replaced the `prefix` parameter with a dynamically generated `solutionPrefix` to ensure unique and consistent naming across resources. This affects multiple variables and resource names, such as `aiServicesName`, `containerApp`, and `aiproject`. (`[[1]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L51-R56)`, `[[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c5 …
> feat: updated tag fnd01 to latest

- infra/main.bicep
- infra/main.json
This pull request updates the service plan configuration for the frontend application in the infrastructure files. The changes primarily focus on downgrading the service plan tier and name to reduce resource allocation.
* In `infra/main.bicep`, the service plan `sku` was downgraded from `P1v2` (PremiumV2 tier) to `B2` (Basic tier). This change reduces the capacity and cost of the service plan.
* In `infra/main.json`, the corresponding `sku` configuration was updated to reflect the same downgrade from `P1v2` (PremiumV2 tier) to `B2` (Basic tier).
* Updated the `_generator.templateHash` in `infra/main.json` to reflect changes made to the Bicep template.
* ...
```
cd [repo-name]
npm install
```
```
```
Verify …
> fix: update App Service SKU from PremiumV2 to Basic (B2)

- infra/main.bicep
- infra/main.bicepparam
- infra/main.json
This pull request makes changes to the infrastructure configuration files to support a new database setup and improve parameter flexibility. The most significant updates include renaming the Cosmos DB database from `autogen` to `macae`, introducing a new parameter for the Azure OpenAI location, and updating dependencies and references accordingly.
* Renamed the Cosmos DB database from `autogen` to `macae` in both `infra/main.bicep` and `infra/main.json` files, including all associated references, such as database IDs, container names, and dependency lists. [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L221-R225) [[2]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L342-R346) …
> fix: Remove autogen reference

- README.md
typo error fixed
```
cd [repo-name]
npm install
```
> fix: typo error fixed

- infra/main.bicep
- infra/main.bicepparam
This pull request introduces several updates to the `infra/main.bicep` file to enhance resource naming consistency, improve regional flexibility, and align with best practices. The key changes include standardizing resource names with a new naming convention, introducing support for specifying Azure OpenAI regions, and updating default locations for specific resources.
* Added a new `AzureOpenAILocation` parameter restricted to supported Azure OpenAI regions and introduced an optional `AZURE_LOCATION` parameter to override the default resource group location. (`[infra/main.bicepL8-R19](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L8-R19)`)
* Updated the `aiFoundryAiServicesConfiguration`, `aiFoundryStorageAccountConfiguration`, …
> refactor: updated the naming conventions for all resources and added AzureOpenAILocation param

- documentation/DeploymentGuide.md
- infra/main.bicep
- infra/main.bicepparam
- infra/modules/container-app-environment.bicep
* Users can now use existing log analytics workspace by setting the bicepparam
```
cd [repo-name]
npm install
```
```
```
* ...
> feat: Implemented reusing of log analytics workspace

- src/backend/app_kernel.py
- src/backend/context/cosmos_memory_kernel.py
- src/backend/handlers/runtime_interrupt_kernel.py
- src/backend/kernel_tools/product_tools.py
- src/backend/middleware/health_check.py
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> feat: clean up logging

- .github/workflows/test-automation.yml
- tests/e2e-test/.gitignore
- tests/e2e-test/README.md
- tests/e2e-test/base/__init__.py
- tests/e2e-test/base/base.py
- tests/e2e-test/config/constants.py
- tests/e2e-test/pages/BIAB.py
- tests/e2e-test/pages/__init__.py
- tests/e2e-test/pages/loginPage.py
- tests/e2e-test/pytest.ini
- tests/e2e-test/requirements.txt
- tests/e2e-test/sample_dotenv_file.txt
- tests/e2e-test/tests/conftest.py
- tests/e2e-test/tests/test_poc_BIAB.py
Migrate test automation scripts and pipeline for MACAE
```
cd [repo-name]
npm install
```
```
```
* ...
> test: Migrate test automation scripts and pipeline for MACAE

- .github/workflows/deploy-waf.yml
* https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/18845/
```
cd [repo-name]
npm install
```
```
```
* ...
> feat:  Automate and validate WAF deployment using pipeline in MACAE accelerator

- .github/workflows/deploy-waf.yml
* This pull request includes a small change to the `.github/workflows/deploy-waf.yml` file. The change increases the `GPT_MIN_CAPACITY` value from `50` to `140` to adjust the minimum capacity configuration for deployment.
```
cd [repo-name]
npm install
```
```
```
* ...
> ci: Update deploy-waf.yml to check for minimum token size required

- infra/main.bicep
* ...
This pull request updates the AI Foundry configuration in `infra/main.bicep` to reduce the model capacity from 140 to 50. This change impacts both the default configuration and the model deployment settings.
Updates to AI Foundry configuration:
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L134-R134): Reduced the default value of `modelCapacity` in `aiFoundryAiServicesConfiguration` from 140 to 50.
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L739-R739): Updated the `capacity` field in `aiFoundryAiServicesModelDeployment` to use the new default value of 50, ensuring consistency with the reduced model capacity.
```
cd …
```
> chore: updated gpt model capacity

- src/backend/app_kernel.py
This pull request includes a minor change to the `src/backend/app_kernel.py` file. The change comments out the line responsible for configuring Azure Monitor using the `APPLICATIONINSIGHTS_CONNECTION_STRING`.
To avoid inconsistent steps of task, commenting configure_azure_monitor
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: fix for inconsistent number of steps of task

- src/frontend_react/public/manifest.json
- src/frontend_react/src/api/apiService.tsx
- src/frontend_react/src/pages/PlanPage.tsx
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: Bug Fix #19398, #19280

- azure.yaml
This pull request updates the `azure.yaml` file to specify a more restrictive version requirement for the `azd` tool.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> docs: Update azure.yaml file

- azure.yaml
- docs/DeploymentGuide.md
This pull request includes a minor update to the `azure.yaml` file. The change refines the `azd` version requirement by excluding version `1.17.1` from compatibility.## Purpose
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> chore: Azd vesion changes Dev to Main

- .github/workflows/deploy.yml
This pull request includes a small change to the `.github/workflows/deploy.yml` file. The change removes the `push` trigger from the workflow configuration.
```
cd [repo-name]
npm install
```
```
```
* ...
> ci: remove push trigger from deploy workflow

- infra/scripts/quota_check_params.sh
- infra/scripts/validate_model_quota.ps1
- infra/scripts/validate_model_quota.sh
* ...
This pull request updates the handling of deployment types for model quota validation scripts to standardize the use of "GlobalStandard" as the default deployment type. The most important changes include modifying default deployment types and removing conditional logic for specific models.
* [`infra/scripts/validate_model_quota.ps1`](diffhunk://#diff-615ff8ddc9e33ac47aeb4d480a276e88a1e4df637c619dde5677f948832d09abL4-R4): Changed the default value of the `DeploymentType` parameter from "Standard" to "GlobalStandard".
* [`infra/scripts/validate_model_quota.sh`](diffhunk://#diff-9e231f4e429fafbe1577c03abd7719d220c9da1cc3e093d70d96fba0aea03466L5-R5): Updated the default value of the `DEPLOYMENT_TYPE` variable from "Standard" to "GlobalStandard".
* …
> chore: migrate model type to global standard

- src/frontend/src/services/WebSocketService.tsx
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix: User Auth header fix

- src/backend/v3/api/router.py
- src/backend/v3/config/settings.py
- src/backend/v3/magentic_agents/proxy_agent.py
- src/backend/v3/models/messages.py
- src/backend/v3/orchestration/human_approval_manager.py
* ... Fix to plan_approval and implement user_clarification functionality
```
cd [repo-name]
npm install
```
```
```
* ...
> feat: Macae v3 dev marktayl

- src/frontend/src/api/apiService.tsx
- src/frontend/src/components/content/PlanChat.tsx
- src/frontend/src/models/plan.tsx
- src/frontend/src/services/PlanDataService.tsx
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> feat: Macae bs sept9

- src/backend/common/database/cosmosdb.py
- src/backend/common/database/database_base.py
- src/backend/v3/api/router.py
- src/frontend/src/components/content/PlanChat.tsx
- src/frontend/src/components/content/PlanChatBody.tsx
- src/frontend/src/components/content/PlanPanelLeft.tsx
- src/frontend/src/components/content/TaskList.tsx
- src/frontend/src/components/content/streaming/StreamingBufferMessage.tsx
- src/frontend/src/models/enums.tsx
- src/frontend/src/models/taskList.tsx
- src/frontend/src/pages/PlanPage.tsx
- src/frontend/src/services/WebSocketService.tsx
Added get_all_plans_by_team_id_status to CosmosDBClient and DatabaseBase for filtering plans by team and status. Updated backend API to use this method for completed plans. Refactored frontend TaskList and related components to remove in-progress tasks and simplify UI, and fixed agent type usage in PlanPage.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Refactor plan retrieval and task list UI

- src/frontend/src/components/content/PlanChat.tsx
- src/frontend/src/components/content/PlanChatBody.tsx
- src/frontend/src/pages/PlanPage.tsx
Added InlineToaster to PlanChat for improved notifications. Adjusted PlanChatBody styling and updated chat input placeholder for clarity. Simplified error handling in PlanPage by removing detailed RAI validation error logic and using a generic error toast.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Update PlanChat UI and simplify error handling

- infra/main.parameters.json
* ... Missing change for test deploy
```
cd [repo-name]
npm install
```
```
```
* ...
> deploy tag change for test

- src/backend/common/utils/utils_kernel.py
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Turn off code interpreter for RAI agent

- src/backend/common/models/messages_kernel.py
- src/backend/v3/api/router.py
- src/backend/v3/common/services/plan_service.py
- src/backend/v3/models/models.py
- src/frontend/src/models/plan.tsx
- src/frontend/src/pages/PlanPage.tsx
- src/frontend/src/services/PlanDataService.tsx
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> Macae v3 fr dev 92

- src/frontend/src/components/content/HomeInput.tsx
- src/frontend/src/components/content/PlanChat.tsx
- src/frontend/src/components/content/PlanChatBody.tsx
- src/frontend/src/components/content/PlanPanelRight.tsx
- src/frontend/src/components/content/streaming/StreamingAgentMessage.tsx
- src/frontend/src/components/content/streaming/StreamingBufferMessage.tsx
- src/frontend/src/components/content/streaming/StreamingPlanResponse.tsx
- src/frontend/src/coral/components/PromptCard.tsx
- src/frontend/src/coral/modules/ChatInput.tsx
- src/frontend/src/pages/PlanPage.tsx
- src/frontend/src/styles/HomeInput.css
- src/frontend/src/styles/PlanChat.css
* ...
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: more UI fixes and buffer message fix

- src/frontend/index.html
- src/frontend/public/index.html
This pull request makes a minor update to the HTML files for the frontend by commenting out the manifest link. This change temporarily disables the web app manifest, which is typically used for Progressive Web App (PWA) features.
* Commented out the `<link rel="manifest" href="/manifest.json" />` line in both `src/frontend/index.html` and `src/frontend/public/index.html` to prevent the manifest from loading. [[1]](diffhunk://#diff-2d5f05d0ad213068f47cc68b8e48f69564a0d02fcd52350d5fdcd47de0c90c80L13-R13) [[2]](diffhunk://#diff-2de919dd74f7847ad17405bdf485fd27e90a86471886db72c082e12ef42620c9L13-R13)
```
cd [repo-name]
npm install
```
```
```
* ...
> fix: commented the manifest.json in index.html to remove the CORS issue

- .github/workflows/deploy-waf.yml
This pull request introduces a minor update to the deployment workflow configuration. The change adds metadata about the creator of the deployment.
* Workflow configuration:
* [`.github/workflows/deploy-waf.yml`](diffhunk://#diff-85b6d7536afbfa792b995f03da08bb9db3e6048413c2406b2d18bf431852eef6R120): Added the `createdBy="Pipeline"` parameter to the deployment step to indicate deployments are initiated by the pipeline.
```
cd [repo-name]
npm install
```
```
```
* ...
> fix:  waf deployment pipeline fix
