src/frontend/wwwroot/task/task.js

While switching pause to start after fetch task details color of status label updated.

fix: in progress status color after fetch task details

---

src/frontend/wwwroot/app.css
src/frontend/wwwroot/task/employee.html
src/frontend/wwwroot/task/task.css

Fix: UX becomes damaged when chat outputs sample code for a task

---

src/backend/agents/base_agent.py
src/backend/agents/group_chat_manager.py
src/backend/agents/human.py
src/backend/agents/planner.py
src/backend/app.py
src/backend/context/cosmos_memory.py

The purpose is to log the custom events into the application insights

Added custom event

---

src/backend/agents/planner.py
src/backend/app.py
src/frontend/wwwroot/home/home.js

The purpose is to fix the task with zero stages cannot show the page, spins forever and RAI test prompts it gives validation, but spinner keeps on loading and running in loop

fix: task with zero stages cannot show the page, spins forever and rai test prompt

---

src/frontend/wwwroot/app.js
src/frontend/wwwroot/home/home.js
src/frontend/wwwroot/task/task.js

* Handled error in the JS files and removed the logs
```
cd [repo-name]
npm install
```
```
```
* ...

fix: error handled and removed console logs from the front-end code

---

src/frontend/wwwroot/app.css

This pull request includes a change to the `src/frontend/wwwroot/app.css` file to improve the menu list's scroll behavior. The most important change is the modification of the `max-height` property for the `.menu-list` class.
Styling adjustments:
* [`src/frontend/wwwroot/app.css`](diffhunk://#diff-ff4d53ae9345a628a61542105398e8d6b30e1ca9ebf086b3dde29ac51dbec561L214-R214): Changed the `max-height` of the `.menu-list` class from a fixed value of `300px` to a dynamic calculation of `calc(100vh - 450px)` to ensure better responsiveness and usability.
Before fix:
After fix:

fix: ui issue where, after creating more than 4 tasks, the 5th task does not appear

---

.github/workflows/create-release.yml
.github/workflows/deploy.yml
.github/workflows/docker-build-and-push.yml
.github/workflows/pr-title-checker.yml
.github/workflows/pylint.yml
.github/workflows/stale-bot.yml

This pull request includes several renaming changes to various workflow files in the `.github/workflows` directory to improve consistency and readability.
Changes to workflow names:
* [`.github/workflows/create-release.yml`](diffhunk://#diff-8ac33fe295df086d3e55df1eb01194819d34cc0f5f54076dba96ceac0e40bd79L10-R10): Changed workflow name from `create-release` to `Create-Release`.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L1-R8): Changed workflow name from `CI-Validate Deployment-Multi-Agent-Custom-Automation-Engine-Solution-Accelerator` to `Validate Deployment` and updated the cron schedule.
* [`.github/workflows/docker-build-and-push.yml`](diffhunk://#diff-4c9cc7fae5379a513fa294daa6c13154c0c512e832a10d7ff36a651aa54129 …

chore: Updated workflow names and trigger schedule

---

.github/workflows/deploy.yml
deploy/scripts/checkquota.sh

Add the variable **AZURE_REGIONS** with the value: eastus eastus2
Purpose:
This pull request includes changes to the deployment workflow and the `checkquota.sh` script to enhance flexibility and ensure required environment variables are set. The most important changes include adding a new environment variable for Azure regions and updating the script to dynamically read regions from this variable.
Improvements to deployment workflow and script:
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R25): Added `AZURE_REGIONS` environment variable to the deployment workflow to allow specifying Azure regions dynamically.
* [`deploy/scripts/checkquota.sh`](diffhunk://#diff-4770a7ba509aa12018b79c9b3cf5bf22cab945f672e887c72c7a953f8a65 …

fix: quota check script with dynamic region handling

---

src/frontend/wwwroot/task/task.js

* After pausing the task, if user input is provided, status changes to in-progress along with the icon. 
```
cd [repo-name]
npm install
```
```
```
* ...

fix: After pausing the task, if user input is provided, status changes to in-progress but pause icon remains same at the top

---

.github/workflows/docker-build-and-push.yml

This pull request includes a change to the `.github/workflows/docker-build-and-push.yml` file to simplify the workflow conditions for logging into the Azure Container Registry.
Workflow simplification:
* [`.github/workflows/docker-build-and-push.yml`](diffhunk://#diff-4c9cc7fae5379a513fa294daa6c13154c0c512e832a10d7ff36a651aa54129f5L35): Removed the conditional statement for logging into the Azure Container Registry, which previously checked if the event name was 'push' and the branch was 'main', 'dev', 'demo', or 'hotfix'.

fix: removed the condition from docker login step

---

src/frontend/wwwroot/app.js
src/frontend/wwwroot/home/home.js
src/frontend/wwwroot/task/task.js
src/frontend/wwwroot/utils.js

When accessing a task page through a copied URL from one browser tab to another, the task information fails to load. The page shows a loading spinner indefinitely, and the task details are not displayed. Upon inspection, it's found that the task ID is missing in session storage.
1. Open the application in one browser tab.
2. Navigate to a task and select a specific task (the URL should change to reflect the task ID).
3. Copy the URL from the browser’s address bar.
4. Open a new tab in the same browser.
5. Paste the copied URL in the new tab and press enter.
6. The session storage should retain the correct task ID, ensuring the task data is fetched properly
```
cd [repo-name]
npm install
```
The task page should load with the task …

fix: Task page does not load properly when URL is copied from one tab to another

---

src/frontend/frontend_server.py
src/frontend/wwwroot/app.js
src/frontend/wwwroot/utils.js

This pull request introduces changes to the frontend server and JavaScript files to support a new configuration option for enabling or disabling authentication. The most important changes include adding an environment variable for authentication, updating the frontend to handle this new configuration, and providing mock user details when authentication is disabled.
Changes to support authentication configuration:
* [`src/frontend/frontend_server.py`](diffhunk://#diff-163320c83714f7af2dd9c8332e03a952c7ec5418861fe4202b3d1fe471de49a3L31-R35): Added a new environment variable `AUTH_ENABLED` to the configuration endpoint.
Frontend updates for handling authentication:
* [`src/frontend/wwwroot/app.js`](diffhunk://#diff-175bf0499a475fa98cecbc6a3042de6e78bd690287d0999228a3a5da58fceb0cR10-R13): …

refactor: Added Flag-Based Authentication Control (AUTH_ENABLED)

---

src/backend/app_kernel.py
src/backend/kernel_agents/agent_factory.py
src/backend/kernel_agents/planner_agent.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix creating tasks

---

src/backend/app_kernel.py
src/backend/config_kernel.py
src/backend/kernel_agents/agent_base.py
src/backend/kernel_agents/agent_factory.py
src/backend/kernel_agents/group_chat_manager.py
src/backend/kernel_agents/planner_agent.py
src/backend/models/messages_kernel.py
src/backend/utils_kernel.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

create task flow

---

src/backend/kernel_agents/planner_agent.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Clean up planner 

---

azure.yaml
infra/deploy_ai_foundry.bicep
infra/main.bicep

* ...
- [ x ] No
```
cd [repo-name]
azd up
```
Check RBAC permissions and env vars on back end container app
```
```
* ...

fix: fixes to params and addition of env vars and RBAC for deployment scripts

---

src/backend/agents/base_agent.py
src/backend/agents/group_chat_manager.py
src/backend/agents/human.py
src/backend/agents/planner.py
src/backend/app_kernel.py
src/backend/models/messages.py
src/backend/tests/test_group_chat_manager_integration.py
src/backend/utils_kernel.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Finished name conversions

---

src/backend/kernel_agents/agent_base.py
src/backend/kernel_agents/group_chat_manager.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fixing invoke

---

src/backend/app_kernel.py
src/backend/kernel_agents/agent_base.py
src/backend/kernel_agents/agent_factory.py
src/backend/kernel_agents/generic_agent.py
src/backend/kernel_agents/group_chat_manager.py
src/backend/kernel_agents/hr_agent.py
src/backend/kernel_agents/human_agent.py
src/backend/kernel_agents/marketing_agent.py
src/backend/kernel_agents/planner_agent.py
src/backend/kernel_agents/procurement_agent.py
src/backend/kernel_agents/product_agent.py
src/backend/kernel_agents/tech_support_agent.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: agents message 

---

infra/main.bicep

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

last conflict 

---

.github/workflows/deploy.yml
azure.yaml
infra/deploy_ai_foundry.bicep
infra/main.bicep
infra/main.json

* This pull request updates the deployment workflow configuration to reflect a reorganization of the project directory structure. Specifically, deployment-related scripts and templates have been moved from the `deploy` directory to a new `infra` directory.
Directory structure updates in `.github/workflows/deploy.yml`:
* Updated the path to the quota check script from `deploy/scripts/checkquota.sh` to `infra/scripts/checkquota.sh` in the `jobs` section. This includes changes to the script execution and error handling logic.
* Updated the path to the deployment template file from `deploy/macae.bicep` to `infra/macae.bicep` in the `jobs` section. This ensures the workflow uses the updated file location for resource deployment.
```
cd [repo-name]
git …
```

ci: Merging dev to main 

---

.github/workflows/azure-dev.yml

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Gpickett patch 2

---

.github/workflows/deploy.yml
infra/scripts/checkquota.sh

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Validate deployment pipeline fix with quota check

---

.github/workflows/docker-build-and-push.yml

This pull request updates the `.github/workflows/docker-build-and-push.yml` file to improve the Docker build and push process by introducing historical tagging, modularizing the workflow, and enhancing readability. The most important changes include adding historical tags for Docker images, splitting backend and frontend build steps, and replacing inline shell scripts with reusable GitHub Actions.
* **Historical Tagging for Docker Images**: Introduced a `HISTORICAL_TAG` environment variable that combines the branch-based tag, the current date, and the GitHub run ID to create unique historical tags for Docker images.
* **Modularized Backend and Frontend Builds**: Replaced the monolithic Docker build-and-push script with separate steps for backend and frontend builds, using …

feat: Add historical tagging and use build-push-action for Docker image build and push

---

.github/workflows/deploy.yml

* ...
This pull request includes a minor update to the `.github/workflows/deploy.yml` file. The change modifies the default account name used for generating a unique resource group name in the deployment workflow.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L76-R76): Updated the `ACCL_NAME` variable from `"ci-biab"` to `"ci-macae"` in the `generate_rg_name` step to reflect the new account naming convention.
```
cd [repo-name]
npm install
```
```
```
* ...

fix: changed resource group accl_name from biab to macae

---

.flake8
.github/workflows/docker-build-and-push.yml
src/backend/app_config.py
src/backend/app_kernel.py
src/backend/config_kernel.py
src/backend/context/cosmos_memory_kernel.py
src/backend/handlers/runtime_interrupt_kernel.py
src/backend/kernel_agents/agent_base.py
src/backend/kernel_agents/agent_factory.py
src/backend/kernel_agents/agent_utils.py
src/backend/kernel_agents/generic_agent.py
src/backend/kernel_agents/group_chat_manager.py
src/backend/kernel_agents/hr_agent.py
src/backend/kernel_agents/human_agent.py
src/backend/kernel_agents/marketing_agent.py
src/backend/kernel_agents/planner_agent.py
src/backend/kernel_agents/procurement_agent.py
src/backend/kernel_agents/product_agent.py
src/backend/kernel_agents/tech_support_agent.py
src/backend/kernel_tools/generic_tools.py
src/backend/kernel_tools/hr_tools.py
src/backend/kernel_tools/marketing_tools.py
src/backend/kernel_tools/procurement_tools.py
src/backend/kernel_tools/product_tools.py
src/backend/kernel_tools/tech_support_tools.py
src/backend/models/messages_kernel.py
src/backend/utils_kernel.py

This pull request focuses on cleaning up unused imports and simplifying code across multiple files in the backend, specifically in agent-related modules and utility tools. The changes aim to improve code readability, reduce clutter, and ensure compatibility with updated dependencies. Below is a summary of the most important changes grouped by theme:
* Removed unused imports such as `semantic_kernel`, `KernelArguments`, and other redundant dependencies across multiple files, including `app_config.py`, `app_kernel.py`, and various agent files (e.g., `agent_base.py`, `human_agent.py`) to streamline the codebase. [[1]](diffhunk://#diff-b41f8ef37e47b480c7fa88bcff65f7647b9dc591cf0263d28d10cf458e359845L4-L10) [[2]](diffhunk://#diff-c839d97b372f2799977f9f197d6c18667f795b2566b1b2c42e27b1479be26173L …

fix: PyLint Issue Fix

---

infra/deploy_ai_foundry.bicep
infra/main.bicep
infra/main.json

This pull request introduces several changes to the `infra` deployment files for AI Foundry. The updates primarily focus on transitioning the AI services authentication method from API key-based to Azure Active Directory (AAD), modifying parameter handling, and adding new role assignments for AI projects. Below is a categorized summary of the most important changes:
* Changed the `authType` for AI services from `'ApiKey'` to `'AAD'` in the `aiHub` resource definition, and removed the `credentials` block that previously used the API key. (`infra/deploy_ai_foundry.bicep`, `infra/main.json`) [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L136-L140) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L770-L774)
* …

fix: fix for disablelocalauth issue 

---

src/backend/kernel_agents/planner_agent.py

This pull request updates the `_get_template` method in `planner_agent.py` to enhance the clarity and completeness of task planning. The changes focus on improving how missing information is identified and handled when generating a plan.
* Updated `_get_template` in `planner_agent.py` to explicitly list the types of required input (e.g., input data, questions, referenced materials) that should be considered when identifying missing information.
* Added a guideline to generate concise clarification requests in the `human_clarification_request` field if required input is missing, even if not explicitly mentioned.

fix: generic agent prompt issue

---

.github/workflows/docker-build-and-push.yml

* ...
This pull request updates the Docker build and push workflow to dynamically determine the container registry URL, improving flexibility and maintainability. The changes include introducing a new step to fetch the registry URL and updating the Docker image tags to use this dynamic value.
* [`.github/workflows/docker-build-and-push.yml`](diffhunk://#diff-4c9cc7fae5379a513fa294daa6c13154c0c512e832a10d7ff36a651aa54129f5R46-R50): Added a new step, "Get registry," to dynamically set the container registry URL using the `ACR_LOGIN_SERVER` secret or a default value (`acrlogin.azurecr.io`).
* [`.github/workflows/docker-build-and-push.yml`](diffhunk://#diff-4c9cc7fae5379a513fa294daa6c13154c0c512e832a10d7ff36a651aa54129f5R73-R83): Updated the Docker image tags for both backend and frontend …

fix: pipeline error for tag not found has been fixed

---

src/backend/app_kernel.py
src/backend/kernel_agents/planner_agent.py
src/frontend/wwwroot/home/home.js

This pull request introduces enhanced error handling for rate limit scenarios and improves error messaging across the backend and frontend. The changes aim to provide more informative feedback to users and developers when encountering specific errors, such as rate limits or plan creation issues.
* [`src/backend/app_kernel.py`](diffhunk://#diff-c839d97b372f2799977f9f197d6c18667f795b2566b1b2c42e27b1479be26173L188-R188): Updated the `input_task_endpoint` to include the exception message in the HTTP error response for better debugging.
* [`src/backend/kernel_agents/planner_agent.py`](diffhunk://#diff-26fed13874b0912fe85301592ef349a3ac2979e6791f384ff7aaacf87ab8b5d1R437-R444): Added logic to detect rate limit errors, log a warning suggesting retrying later, and raise the exception explicitly. …

feat: added rate limit error pop up

---

infra/main.bicep

This pull request makes adjustments to the configuration of various Azure resources in the `infra/main.bicep` file to enhance security and simplify deployment. The key changes involve disabling public blob access, ensuring non-zone-redundant setups, and standardizing configurations across modules.
Updated the `aiFoundryStorageAccount` module to always disable blob public access, regardless of the `virtualNetworkEnabled` setting.
Added `isZoneRedundant: false` to the `cosmosDb` module configuration to explicitly disable zone redundancy.
Modified the `containerAppEnvironment` module to set `zoneRedundant` to `false`, removing conditional logic based on `virtualNetworkEnabled`.## Purpose
```
cd [repo-name]
npm install
```
* …

fix: Disable Zone Redundancy 

---

src/frontend_react/src/components/content/HomeInput.tsx
src/frontend_react/src/components/content/PlanChat.tsx
src/frontend_react/src/components/content/PlanPanelLeft.tsx
src/frontend_react/src/components/toast/InlineToaster.tsx
src/frontend_react/src/coral/components/Panels/PanelLeftToolbar.tsx
src/frontend_react/src/coral/components/PromptCard.tsx
src/frontend_react/src/pages/PlanPage.tsx
src/frontend_react/src/styles/Chat.css
src/frontend_react/src/styles/PlanPage.css

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

UI ux refresh eunsoo

---

src/frontend_react/src/components/content/PlanChat.tsx
src/frontend_react/src/components/content/PlanPanelLeft.tsx
src/frontend_react/src/components/content/TaskDetails.tsx
src/frontend_react/src/components/content/TaskList.tsx
src/frontend_react/src/coral/components/CoralAccordion/CoralAccordionHeader.tsx
src/frontend_react/src/coral/components/Progress/ProgressCircle.tsx
src/frontend_react/src/pages/HomePage.tsx
src/frontend_react/src/pages/PlanPage.tsx
src/frontend_react/src/styles/Chat.css
src/frontend_react/src/styles/PlanChat.css
src/frontend_react/src/styles/PlanPanelLeft.css
src/frontend_react/src/styles/TaskDetails.css
src/frontend_react/src/styles/TaskList.css

- Scroll to bottom on load and new message
- Task / Subtask visual haul
- Carats in PanelLeft fixed
- Shortened task titles
- Removed Content panel title icons
- Sample data... visual haul
- Progress ring is now a Coral component
* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Major changes

---

docs/DeploymentGuide.md
docs/LocalDeployment.md

This pull request updates documentation files to reflect changes in role naming conventions and backend application execution commands. The most important changes include updates to Azure role assignments and adjustments to the commands for running the backend application.
Updates to Azure role assignments:
* [`docs/DeploymentGuide.md`](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9dafb6a4185d382bba81c4093aaaded7cL321-R321): Changed the role name from "Cognitive Services OpenAI User" to "Azure AI User" in the Azure CLI command for role assignment.
* [`docs/LocalDeployment.md`](diffhunk://#diff-c347f0751112e9a252055cf0dad2a4fc1eb18034e3255432a1b073cabe634f51L95-R95): Updated the role name in the Azure CLI command for role assignment to match the new naming convention.
Updates to backend …

fix: Updated readme for role assignment and file name

---

src/backend/app_kernel.py

* This pull request re-enables Azure Application Insights monitoring in the `app_kernel.py` file by uncommenting previously disabled code. The changes ensure that telemetry data is sent to Azure when the appropriate connection string is provided.
Azure Application Insights monitoring:
* [`src/backend/app_kernel.py`](diffhunk://#diff-c839d97b372f2799977f9f197d6c18667f795b2566b1b2c42e27b1479be26173L13-R13): Re-enabled the import of `configure_azure_monitor` from `azure.monitor.opentelemetry` by uncommenting the import statement.
* [`src/backend/app_kernel.py`](diffhunk://#diff-c839d97b372f2799977f9f197d6c18667f795b2566b1b2c42e27b1479be26173L41-R41): Re-enabled the call to `configure_azure_monitor` with the `connection_string` parameter, ensuring that Application Insights is configured when …

fix: enable the appinsights telemetry logs code 

---

docs/CustomizingAzdParameters.md
infra/main.bicep
infra/main.parameters.json
infra/modules/account/main.bicep
infra/modules/account/modules/dependencies.bicep
infra/modules/account/modules/keyVaultExport.bicep
infra/modules/account/modules/project.bicep
infra/modules/role.bicep

This pull request introduces significant updates to the `infra/main.bicep` file and its dependent modules, focusing on enhancing AI Foundry project support, improving resource configurations, and cleaning up unused or redundant code. Key changes include adding support for existing AI Foundry projects, introducing new modules for role assignments and Key Vault exports, and removing deprecated or unnecessary configurations.
* **Support for existing AI Foundry projects**: Added the `existingFoundryProjectResourceId` parameter to allow the use of pre-existing AI Foundry projects. Updated logic to dynamically handle existing or new projects in the `infra/main.bicep` file. [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4R7-R9) …

chore: Reuse Ai Foundry for MACAE

---

docs/re-use-log-analytics.md

Updated link
Link update
Link update

docs: Update re-use-log-analytics.md for link update

---

docs/NON_DEVCONTAINER_SETUP.md
next-steps.md

added file NON_DEVCONTAINER_SETUP.md and changed path of resources.bicep file
```
cd [repo-name]
npm install
```
```
```
* ...

docs: added file NON_DEVCONTAINER_SETUP.md and changed path of resources.bicep file

---

src/frontend/src/components/content/TaskDetails.tsx

This pull request updates the `TaskDetails` component in the `src/frontend/src/components/content/TaskDetails.tsx` file to improve user interaction by dynamically adjusting tooltip content based on the `canInteract` state.
Enhancements to user interaction:
* Updated the tooltip for the "Approve" button to display "You must first provide feedback to the planner" when `canInteract` is `false`, enhancing clarity for users who cannot interact yet.
* Updated the tooltip for the "Reject" button to display "You must first provide feedback to the planner" when `canInteract` is `false`, ensuring consistent messaging across action buttons.
```
cd [repo-name]
npm install
```
```
```
Verify that the following are …

fix: Macae bug fixes for tooltip

---

azure.yaml
docs/DeploymentGuide.md

This pull request includes updates to ensure compatibility with the latest version of the Azure Developer CLI (azd) and improves documentation clarity regarding version requirements.
```
cd [repo-name]
npm install
```
```
```
* ...
This pull request introduces a version requirement for the Azure Developer CLI (`azd`) in both the `azure.yaml` configuration file and the deployment guide documentation. This ensures compatibility and clarity for users setting up the project.
* [`azure.yaml`](diffhunk://#diff-1ba5bd52036276068bc787a1be3dfa49aa920317ab02fa460c99246a78e588f3R5-R6): Added a `requiredVersions` field specifying that `azd` version 1.15.0 or higher is required.
* …

docs: added required azd version in azure.yml file and updated DeploymentGuide.md file

---

src/frontend/src/components/content/TaskDetails.tsx

This pull request enhances the functionality of the `TaskDetails` component by introducing asynchronous handling and loading states for approval and rejection actions. These changes improve user experience by preventing multiple interactions while an action is being processed.
* **Approval Button Logic**:
- Updated the `onClick` handler for the approval button to use an asynchronous function. This function sets a loading state for the corresponding step, calls the `preOnApproved` function, and ensures the loading state is removed after the API call completes.
- Added a `disabled` attribute to prevent interaction when the step is loading or when `canInteract` is false.
* **Rejection Button Logic**:
- Updated the `onClick` handler for the rejection button to use an asynchronous function, …

fix: Bug fix of #20489

---

infra/main.bicep

This pull request adds a new resource definition for tagging a resource group in the `infra/main.bicep` file. The change introduces a `resourceGroupTags` resource to apply tags, including a new `templateName` tag with the value "Macae."
Key changes:
* Added a `resourceGroupTags` resource of type `Microsoft.Resources/tags@2021-04-01` to define and apply tags to the resource group. This includes merging existing tags and adding a `templateName` tag with the value "Macae." (`[infra/main.bicepR235-R244](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4R235-R244)`)* ...
```
cd [repo-name]
npm install
```
```
```
* ...

feat: Added templateName tag on rg

---

.github/workflows/deploy-waf.yml
.github/workflows/deploy.yml
infra/main.bicep
infra/main.parameters.json

* This pull request updates the infrastructure configuration in `infra/main.bicep` and `infra/main.parameters.json` to improve parameter clarity and align resource naming conventions with the environment name. The most important changes include replacing the `solutionPrefix` parameter with `environmentName`, introducing a new `solutionPrefix` definition, and adding empty zones to the bastion host configuration.
* Replaced the `solutionPrefix` parameter with a new `environmentName` parameter to specify the deployment environment name, making it a required field. (`infra/main.bicep`, [infra/main.bicepL10-R11](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L10-R11))
* Added a new `solutionPrefix` definition based on the `environmentName`, subscription ID, …

fix: telemetry error fix

---

infra/modules/role.bicep
infra/old/deploy_ai_foundry.bicep
infra/old/main.bicep

* This pull request introduces a consistent update across multiple Bicep files to specify the `principalType` as `'ServicePrincipal'` in role assignment resources. This change ensures clarity and consistency in defining the type of principal for role assignments.
* `infra/modules/role.bicep`: Added `principalType: 'ServicePrincipal'` to the `properties` block for the following resources:
- `aiUserAccessFoundry`
- `aiDeveloperAccessFoundry`
- `cognitiveServiceOpenAIUserAccessFoundry`
* [`infra/old/deploy_ai_foundry.bicep`](diffhunk://#diff-81cf0ed7ae35750a61fd712c20c3c6507ff27191d007405227635f184b814392R172): Added `principalType: 'ServicePrincipal'` to the `properties` block for the `aiDevelopertoAIProject` role assignment.
* `infra/old/main.bicep`: Added `principalType: …

fix: add principalType as 'ServicePrincipal' for role assignments

---

infra/main.bicep
src/backend/kernel_agents/agent_base.py

This pull request includes a small but important change to the `infra/main.bicep` file. It modifies the `solutionPrefix` parameter to include the resource group's name as part of the unique string generation, ensuring better differentiation of resources across deployments.
* [`infra/main.bicep`](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L50-R50): Updated the `solutionPrefix` parameter to include `resourceGroup().name` in the unique string generation for improved resource identification.## Purpose
* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: Prefix/Suffix fixes - dev to main

---

src/frontend/src/index.tsx

This pull request makes a minor adjustment to the `AppWrapper` component in `src/index.tsx` by moving the `sendUserBrowserLanguage` API call to a different location within the `try` block to improve execution order and error handling.
Key change:
* The `sendUserBrowserLanguage` API call was relocated from before the `try` block to within the `try` block, after setting the default user information. This ensures the call is made only if earlier operations succeed, improving error handling and logical flow. (`[[1]](diffhunk://#diff-d2f8515a5da5fdbaafcfe7f5be649fa68b891afe926f96bcc71a2d247cba04dfL26)`, `[[2]](diffhunk://#diff-d2f8515a5da5fdbaafcfe7f5be649fa68b891afe926f96bcc71a2d247cba04dfL42-R41)`)
```
cd [repo-name]
npm …
```

fix: bug fix

---

docs/LocalDeployment.md

* ...
This pull request updates the local deployment documentation to clarify how to set up the `.env` file for the backend. It adds instructions for both manual and automated provisioning scenarios.
Documentation improvements:
* Clarified that the `.env` file for `src\backend` should be updated with values from Azure App Service environment variables.
* Added instructions that if resources are provisioned using `azd provision` or `azd up`, the `.env` file is automatically generated in `.azure/<env-name>/.env`, and provided guidance on how to find the `<env-name>`.
```
cd [repo-name]
npm install
```
```
```
* ...

docs: updated env in readme local setup

---

src/backend/kernel_agents/planner_agent.py

This pull request makes a small update to the planner agent's template prompt. The main change is to instruct the agent to first ask the user for any additional information needed before proceeding with the rest of the planned steps. 
([src/backend/kernel_agents/planner_agent.py](diffhunk://#diff-26fed13874b0912fe85301592ef349a3ac2979e6791f384ff7aaacf87ab8b5d1R571))
```
cd [repo-name]
npm install
```
```
```
* ...

fix: reverted the original prompt of planner agent

---

docs/CustomizingAzdParameters.md
docs/DeploymentGuide.md
infra/main.bicep
infra/main.parameters.json
infra/main.waf.parameters.json

* This pull request introduces documentation and configuration improvements for VM credential management, environment parameter defaults, and deployment guidance for the Azure Developer CLI (azd). The changes clarify how to set VM administrator credentials, update default environment variable usage, and improve instructions for sandbox and production deployments. Additionally, there are fixes to ensure correct resource location handling in infrastructure provisioning.
**Documentation enhancements:**
* Added instructions for configuring VM administrator username and password via environment variables in `docs/DeploymentGuide.md`, with guidance for setting custom credentials before deployment.
* Updated `docs/CustomizingAzdParameters.md` to include new parameters for VM admin username and …

fix: update README and align Data Collection Rule location with workspace

---

src/backend/common/utils/utils_kernel.py
src/backend/v3/common/services/foundry_service.py
src/backend/v3/config/settings.py
src/backend/v3/magentic_agents/reasoning_agent.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

feat: define the correct service to get the token

---

.github/workflows/deploy.yml

This pull request modifies the deployment workflow to improve clarity and flexibility in specifying container image tags for backend and frontend services.
Deployment workflow update:
* In `.github/workflows/deploy.yml`, replaces the single `imageTag` parameter with `backendContainerImageTag` and `frontendContainerImageTag` to separately specify image tags for backend and frontend containers during deployment.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...

ci: Update image tags for backend and frontend containers

---

src/backend/v3/callbacks/response_handlers.py
src/backend/v3/magentic_agents/proxy_agent.py
src/backend/v3/models/messages.py

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Strongly typed messages - sent tool call info

---

src/backend/v3/models/messages.py
src/frontend/src/services/PlanDataService.tsx

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Macae v3 fr dev 92

---

src/backend/common/utils/utils_kernel.py
src/backend/v3/api/router.py

* ...
Switched to agent based RAI check to improve test results
```
cd [repo-name]
npm install
```
```
```
* ...

Macae v3 dev marktayl

---

src/frontend/src/components/content/PlanChatBody.tsx
src/frontend/src/components/content/streaming/StreamingAgentMessage.tsx
src/frontend/src/components/content/streaming/StreamingBufferMessage.tsx
src/frontend/src/components/content/streaming/StreamingPlanResponse.tsx
src/frontend/src/components/content/streaming/StreamingPlanState.tsx
src/frontend/src/components/content/streaming/StreamingUserPlanMessage.tsx

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

feat: implement consistent UI styling across streaming components

---

src/frontend/src/components/content/streaming/StreamingAgentMessage.tsx
src/frontend/src/utils/agentIconUtils.tsx

* ...
```
cd [repo-name]
npm install
```
```
```
* ...

fix: human clarification text color

---

src/frontend/src/components/content/PlanPanelRight.tsx
src/frontend/src/styles/planpanelright.css

Replaced inline styles in PlanPanelRight.tsx with CSS classes and added a dedicated stylesheet (planpanelright.css) for improved maintainability and responsiveness. This change makes the component styling more consistent and easier to manage, with media queries for better display on various screen sizes.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...

Refactor PlanPanelRight to use CSS classes

---

src/backend/common/database/cosmosdb.py
src/backend/common/database/database_base.py
src/backend/v3/api/router.py

This pull request updates the way plans are retrieved by team and status to require a `user_id` parameter instead of relying on an internal value. The change ensures that queries for plans are correctly filtered by user, improving data accuracy and consistency across the API and database layers.
**Database and API consistency improvements:**
* Updated the abstract method signature in `database_base.py` to require a `user_id` parameter for retrieving plans by team and status, ensuring all implementations follow the same contract.
* Modified the implementation in `cosmosdb.py` to accept `user_id` as an argument and use it in the query parameters, rather than relying on an internal instance value.
* Updated the API endpoint in `router.py` to pass the `user_id` argument when retrieving …

fix: Added the user_id explicitly to get the completed task

---

docs/quota_check.md

Added a step to navigate to the 'infra' directory before accessing the 'scripts' folder.
This pull request makes a minor update to the documentation, clarifying the correct navigation steps for running quota check scripts.
* In `docs/quota_check.md`, added a step to change into the `infra` directory before entering the `scripts` folder, improving instructions for locating and executing the script.
* ...
```
cd [repo-name]
npm install
```
```
```
* ...

docs: clarify navigation by adding step to enter 'infra' directory before 'scripts'

---

README.md
azure.yaml
docs/DeploymentGuide.md

This pull request updates the minimum required version of the Azure Developer CLI (azd) to 1.18.0 and ensures this requirement is clearly documented throughout the project. The changes help prevent deployment issues by making sure users are aware of and use the correct CLI version.
Requirements and documentation updates:
* Updated the `azure.yaml` configuration file to require `azd` version 1.18.0 or higher, removing support for earlier versions.
* Revised the installation instructions in `docs/DeploymentGuide.md` to specify `azd` v1.18.0+ as a prerequisite.
* Added prominent notes in both `README.md` and `docs/DeploymentGuide.md` to inform users about the new `azd` version requirement and provide a direct download link. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6 …

docs: Updated README, azure.yml for minimum azd version 1.18.0

---

README.md
azure.yaml
docs/DeploymentGuide.md

This pull request updates the required version of the Azure Developer CLI (`azd`) for deploying the solution accelerator. All documentation and configuration references to `azd` have been updated to require version 1.18.0 or higher, and additional notes have been added to help users ensure they have the correct version installed.
**Updates to required tooling and documentation:**
* Increased the minimum required version of `azd` to 1.18.0 in the `azure.yaml` configuration file, removing support for earlier versions.
* Updated all documentation references in `docs/DeploymentGuide.md` to specify `azd` version 1.18.0 or higher, replacing the previous 1.15.0+ requirement.
* Added prominent notes in both the `README.md` and `docs/DeploymentGuide.md` to inform users about the new `azd` version …

docs: Updated README, azure.yml for minimum azd version 1.18.0Psl azd version upgrade
